name: todoapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  gap: ^3.0.1
  fluttertoast: ^8.2.6
  firebase_database: ^11.0.3
  shared_preferences: ^2.2.3
  auto_size_text_field: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  audioplayers: ^6.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/file.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
